project:
  type: book
  output-dir: docs

book:
  title: "Morris Research Team Lab Manual"
  site-url: https://drearlthe4th.github.io/lab-manual/
  chapters:
    - index.qmd
    - intro-how-we-work.qmd
    - culture-philosophy.qmd
    - code-of-conduct.qmd
    - onboarding.qmd
    - expectations.qmd
    - offboarding.qmd
    - funding.qmd
    - communication.qmd
    - academics.qmd
    - courses.qmd
    - conferences.qmd
    - papers.qmd
    - computing.qmd
    - data_resources.qmd
    - coding_resources.qmd


format:
  html:
    theme:
      - cosmo
      - styles/labmanual.scss
    toc: true
    toc-depth: 3
    number-sections: false
