project:
  type: website
  output-dir: docs

website:
  title: "Morris Lab Manual"
  site-url: https://drearlthe4th.github.io/lab-manual/
  search: true

format:
  html:
    theme:
      - cosmo
    toc: true
